server:
  port: 9090

spring:
  application:
    name: CrudJPA
  # Conexion con la base de datos
  datasource:
    url: jdbc:mysql://localhost:3306/db_springboot
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #Configuracion con la base de datos
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    # ¡Solo para desarrollo!
    hibernate:
      ddl-auto: update
    #fin solo para desarrollo
